In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("movies.csv")

In [4]:
data.head()

   srno                 movie  year  rating    time
0     1  The Nightmare Before  1993     3.9  4568.0
1     2             The Mummy  1932     3.5  4388.0
2     3  Orphans of the Storm  1921     3.2  9062.0
3     4  The Object of Beauty  1991     2.8  6150.0
4     5            Night Tide  1963     2.8  5126.0

In [5]:
data.tail()

,srno,movie,year,rating,time
49585,49586,Winter Wonderland,2013,2.8,1812.0
49586,49587,Top Gear: Series 19: Africa Special,2013,NaN,6822.0
49587,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,NaN,3610.0
49588,49589,Kate Plus Ei8ht,2010,2.7,NaN
49589,49590,Kate Plus Ei8ht: Season 1,2010,2.7,NaN

In [6]:
data.describe()

               srno          year        rating          time
count  49590.000000  49590.000000  10814.000000  45836.000000
mean   24795.500000   2002.303428      3.451248   2628.445436
std    14315.544261     12.534555      0.495601   1604.646265
min        1.000000   1913.000000      1.400000     52.000000
25%    12398.250000   1999.000000      3.100000   1356.000000
50%    24795.500000   2007.000000      3.500000   2563.000000
75%    37192.750000   2010.000000      3.800000   2877.000000
max    49590.000000   2014.000000      4.500000  28813.000000

In [7]:
data.shape

(49590, 5)

In [9]:
data.columns

Index(['srno', 'movie', 'year', 'rating', 'time'], dtype='str')

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 49590 entries, 0 to 49589
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   srno    49590 non-null  int64
 1   movie   49590 non-null  str
 2   year    49590 non-null  int64
 3   rating  10814 non-null  float64
 4   time    45836 non-null  float64
dtypes: float64(2), int64(2), str(1)
memory usage: 1.9 MB

In [13]:
#total movies
len(data)

49590

In [15]:
#missing values count
data.isnull().sum()

srno          0
movie         0
year          0
rating    38776
time       3754
dtype: int64

In [24]:
#duplicates values count
data.duplicated().sum()

np.int64(0)

In [25]:
#remove duplicates
data.drop_duplicates()

,srno,movie,year,rating,time
0,1,The Nightmare Before,1993,3.9,4568.0
1,2,The Mummy,1932,3.5,4388.0
2,3,Orphans of the Storm,1921,3.2,9062.0
3,4,The Object of Beauty,1991,2.8,6150.0
4,5,Night Tide,1963,2.8,5126.0
...,...,...,...,...,...
49585,49586,Winter Wonderland,2013,2.8,1812.0
49586,49587,Top Gear: Series 19: Africa Special,2013,NaN,6822.0
49587,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,NaN,3610.0
49588,49589,Kate Plus Ei8ht,2010,2.7,NaN
49589,49590,Kate Plus Ei8ht: Season 1,2010,2.7,NaN

In [44]:
#filtering by rating
data1=data[data["rating"]>4]
data1

,srno,movie,year,rating,time
138,139,Pulp Fiction,1994,4.1,9265.0
287,288,Life Is Beautiful,1997,4.2,6973.0
302,303,Mulan: Special Edition,1998,4.2,5270.0
464,465,Forrest Gump,1994,4.3,8525.0
490,491,Braveheart,1995,4.2,10658.0
...,...,...,...,...,...
49548,49549,Life With Boys: Season 1,2011,4.1,NaN
49553,49554,Max Steel,2013,4.1,NaN
49555,49556,Lilyhammer: Season 1 (Recap),2013,4.2,194.0
49570,49571,The Short Game (Trailer),2013,4.1,156.0
49578,49579,Transformers Prime Beast Hunters: Predacons Ri...,2013,4.2,3950.0

In [45]:
data1.shape

(897, 5)

In [46]:
#filtering by year
data2=data[data["year"]==2000]
data2

,srno,movie,year,rating,time
409,410,Believe,2000,3.3,5767.0
416,417,The Prophecy 3: The Ascent,2000,3.4,5048.0
430,431,Scream 3,2000,3.2,7013.0
431,432,The Tigger Movie,2000,3.5,4626.0
432,433,Holy Smoke,2000,3.0,6855.0
...,...,...,...,...,...
46868,46869,Digimon Adventure: Season 2: Gigantic Ultimate...,2000,NaN,1386.0
46870,46871,Digimon Adventure: Season 2: Steel Angel Shak...,2000,NaN,1386.0
46874,46875,Digimon Adventure: Season 2: Assault! BlackWar...,2000,NaN,1385.0
46876,46877,Digimon Adventure: Season 2: Defend the Holy P...,2000,NaN,1385.0
46877,46878,Digimon Adventure: Season 2: Today Miyako Is i...,2000,NaN,1386.0

In [47]:
data2.shape

(902, 5)

In [52]:
#sorting highest_rating
data.sort_values("rating",ascending=False)

,srno,movie,year,rating,time
14954,14955,Breaking Bad: Season 4,2011,4.5,NaN
14956,14957,Sherlock: Series 1,2010,4.5,NaN
37896,37897,The Walking Dead: Season 3,2012,4.5,NaN
30425,30426,The Avengers,2012,4.5,8575.0
26483,26484,Sherlock,2010,4.5,NaN
...,...,...,...,...,...
49563,49564,My Hope America with Billy Graham: Lose to Gain,2013,NaN,1400.0
49576,49577,Barbie: Life in the Dreamhouse: Barbie Life in...,2013,NaN,1390.0
49577,49578,Barbie: Life in the Dreamhouse: Barbie Life in...,2013,NaN,1458.0
49586,49587,Top Gear: Series 19: Africa Special,2013,NaN,6822.0
49587,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,NaN,3610.0

In [53]:
#sorting lowest_rating
data.sort_values("rating")

,srno,movie,year,rating,time
40934,40935,Lagegi,2007,1.4,NaN
40826,40827,Lagegi,2007,1.4,NaN
42115,42116,Sun Yaar Chill Maar,2007,1.4,NaN
42160,42161,Sun Yaar Chill Maar,2007,1.4,NaN
41396,41397,Meri Toh Lag Gayi Naukri,2011,1.5,NaN
...,...,...,...,...,...
49563,49564,My Hope America with Billy Graham: Lose to Gain,2013,NaN,1400.0
49576,49577,Barbie: Life in the Dreamhouse: Barbie Life in...,2013,NaN,1390.0
49577,49578,Barbie: Life in the Dreamhouse: Barbie Life in...,2013,NaN,1458.0
49586,49587,Top Gear: Series 19: Africa Special,2013,NaN,6822.0
49587,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,NaN,3610.0