In [1]:
#import library
import pandas as pd
import numpy as np

In [3]:
#load data
data=pd.read_csv("car data.csv")

In [4]:
#first 5 rows
data.head()

,ID,model,engine_power,age_in_days,km,previous_owners,lat,lon,price
0,1,lounge,51,882,25000,1,44.907242,8.611560,8900
1,2,pop,51,1186,32500,1,45.666359,12.241890,8800
2,3,sport,74,4658,142228,1,45.503300,11.417840,4200
3,4,lounge,51,2739,160000,1,40.633171,17.634609,6000
4,5,pop,73,3074,106880,1,41.903221,12.495650,5700

In [5]:
#last 5 rows
data.tail()

,ID,model,engine_power,age_in_days,km,previous_owners,lat,lon,price
1515,1534,sport,51,3712,115280,1,45.069679,7.70492,5200
1516,1535,lounge,74,3835,112000,1,45.845692,8.66687,4600
1517,1536,pop,51,2223,60457,1,45.481541,9.41348,7500
1518,1537,lounge,51,2557,80750,1,45.000702,7.68227,5990
1519,1538,pop,51,1766,54276,1,40.323410,17.56827,7900

In [6]:
#dataset information
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               1520 non-null   int64
 1   model            1520 non-null   str
 2   engine_power     1520 non-null   int64
 3   age_in_days      1520 non-null   int64
 4   km               1520 non-null   int64
 5   previous_owners  1520 non-null   int64
 6   lat              1520 non-null   float64
 7   lon              1520 non-null   float64
 8   price            1520 non-null   int64
dtypes: float64(2), int64(6), str(1)
memory usage: 107.0 KB

In [7]:
data.describe()

,ID,engine_power,age_in_days,km,previous_owners,lat,lon,price
count,1520.000000,1520.000000,1520.000000,1520.000000,1520.000000,1520.000000,1520.000000,1520.000000
mean,768.854605,51.915132,1657.190789,53602.474342,1.123684,43.539485,11.571552,8564.311842
std,443.599478,4.010360,1290.870689,40181.202940,0.415901,2.137960,2.332344,1942.771619
min,1.000000,51.000000,366.000000,1232.000000,1.000000,36.855839,7.245400,2500.000000
25%,383.750000,51.000000,670.000000,20000.000000,1.000000,41.794763,9.505090,7100.000000
50%,769.500000,51.000000,1066.000000,39162.000000,1.000000,44.394096,11.869260,9000.000000
75%,1151.250000,51.000000,2623.750000,80000.000000,1.000000,45.467960,12.786127,10000.000000
max,1538.000000,77.000000,4658.000000,235000.000000,4.000000,46.795612,18.365520,11100.000000

In [8]:
#rows and columns count
data.shape

(1520, 9)

In [10]:
#columns names
data.columns

Index(['ID', 'model', 'engine_power', 'age_in_days', 'km', 'previous_owners',
       'lat', 'lon', 'price'],
      dtype='str')

In [11]:
#empty values count
data.isnull().sum()

ID                 0
model              0
engine_power       0
age_in_days        0
km                 0
previous_owners    0
lat                0
lon                0
price              0
dtype: int64

In [12]:
#To use numpy
#average of price
np.mean(data['price'])

np.float64(8564.311842105262)

In [13]:
#highest price
np.max(data['price'])

np.int64(11100)

In [14]:
#lowest price
np.min(data['price'])

np.int64(2500)

In [15]:
#total price
np.sum(data['price'])

np.int64(13017754)

In [18]:
#array 
array_price=np.array(data['price'])
print(array_price)

[8900 8800 4200 ... 7500 5990 7900]

In [19]:
#shape
array_price.shape

(1520,)

In [24]:
# zeros()
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
#ones()
np.ones(4)

array([1., 1., 1., 1.])